# Generated by Django 4.2.7 on 2026-09-04 22:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("due_date", models.DateTimeField()),
                ("max_score", models.IntegerField(default=100)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CampusAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ACADEMIC", "Academic"),
                            ("EMERGENCY", "Emergency"),
                            ("WEATHER", "Weather"),
                            ("FACILITY", "Facility"),
                            ("FINANCE", "Finance"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("ALL", "All"),
                            ("STUDENTS", "Students"),
                            ("FACULTY", "Faculty"),
                            ("STAFF", "Staff"),
                        ],
                        default="ALL",
                        max_length=20,
                    ),
                ),
                ("sender_name", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("active_until", models.DateTimeField()),
                ("channels_sent", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="CampusMediaPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CAMPUS_NEWS", "Campus News"),
                            ("RESEARCH_INNOVATION", "Research Innovation"),
                            ("GRADUATION_CEREMONY", "Graduation Ceremony"),
                            ("TECH_EXPO", "Tech Expo"),
                            ("PRESIDENTIAL_ADDRESS", "Presidential Address"),
                            ("STUDENT_LIFE", "Student Life"),
                        ],
                        max_length=30,
                    ),
                ),
                ("video_url", models.URLField(max_length=500)),
                ("thumbnail_url", models.URLField(max_length=500)),
                ("posted_by", models.CharField(max_length=100)),
                ("author_role", models.CharField(max_length=50)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.CharField(max_length=20)),
                ("views_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("tags", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=20, unique=True)),
                ("course_title", models.CharField(max_length=200)),
                ("credit_hours", models.IntegerField()),
                ("description", models.TextField()),
                ("department", models.CharField(max_length=100)),
                ("semester", models.CharField(max_length=10)),
                ("academic_year", models.IntegerField()),
                ("capacity", models.IntegerField(default=40)),
                ("enrolled_students_count", models.IntegerField(default=0)),
                ("prerequisites", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=200)),
                ("exam_title", models.CharField(max_length=200)),
                ("exam_date", models.DateTimeField()),
                ("duration_minutes", models.IntegerField()),
                ("total_marks", models.IntegerField()),
                ("instructions", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("ACTIVE", "Active"),
                            ("CLOSED", "Closed"),
                            ("GRADED", "Graded"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="App.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacilityBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_name", models.CharField(max_length=100)),
                ("facility_code", models.CharField(max_length=20)),
                (
                    "campus",
                    models.CharField(
                        choices=[
                            ("Tulu Awulia (Main)", "Tulu Awulia (Main)"),
                            ("Masha Campus", "Masha Campus"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("LAB", "Lab"),
                            ("AUDITORIUM", "Auditorium"),
                            ("SEMINAR_ROOM", "Seminar Room"),
                            ("LIBRARY_CUBICLE", "Library Cubicle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("booked_by", models.CharField(max_length=100)),
                ("booked_by_role", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("purpose", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("PENDING", "Pending"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("capacity", models.IntegerField(default=0)),
                ("resources_equipped", models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("course_title", models.CharField(max_length=200)),
                ("course_code", models.CharField(max_length=20)),
                ("credit_hours", models.IntegerField()),
                ("continuous_assessment_score", models.FloatField(default=0)),
                ("mid_exam_score", models.FloatField(default=0)),
                ("final_exam_score", models.FloatField(default=0)),
                ("total_grade", models.FloatField(default=0)),
                ("letter_grade", models.CharField(blank=True, max_length=2)),
                ("grade_point", models.FloatField(default=0)),
                ("semester", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CALCULATED", "Calculated"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("RETURNED", "Returned"),
                        ],
                        default="CALCULATED",
                        max_length=20,
                    ),
                ),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="App.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LibraryResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("isbn", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Computer Science", "Computer Science"),
                            ("Software Engineering", "Software Engineering"),
                            ("Mathematics", "Mathematics"),
                            ("General Engineering", "General Engineering"),
                            ("National Curriculum", "National Curriculum"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("BOOK", "Book"),
                            ("VIDEO", "Video"),
                            ("ARTICLE", "Article"),
                            ("LECTURE_NOTE", "Lecture Note"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("file_size", models.CharField(max_length=50)),
                ("downloads_count", models.IntegerField(default=0)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("STUDENTS_ONLY", "Students Only"),
                            ("FACULTY_ONLY", "Faculty Only"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("uploaded_by", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="MoEAdmissionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("national_exam_roll", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("department_assigned", models.CharField(max_length=100)),
                ("national_exam_score", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ADMITTED", "Admitted"),
                            ("VERIFIED", "Verified"),
                            ("REGISTERED", "Registered"),
                        ],
                        default="ADMITTED",
                        max_length=20,
                    ),
                ),
                ("batch_year", models.IntegerField()),
                ("fayda_national_id", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice"),
                            ("TF", "True/False"),
                            ("short_answer", "Short Answer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(max_length=500)),
                ("marks", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_start", models.DateField()),
                ("semester_end", models.DateField()),
                ("registration_deadline", models.DateField()),
                ("exam_start", models.DateField()),
                ("exam_end", models.DateField()),
                ("grade_a_threshold", models.IntegerField(default=90)),
                ("grade_b_threshold", models.IntegerField(default=80)),
                ("grade_c_threshold", models.IntegerField(default=70)),
                ("grade_d_threshold", models.IntegerField(default=60)),
                ("academic_year_frozen", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("INSTRUCTOR", "Instructor"),
                            ("REGISTRAR", "Registrar"),
                            ("DEPARTMENT_HEAD", "Department Head"),
                            ("ADMIN", "Admin"),
                            ("DEAN", "Dean"),
                            ("AUDITOR", "Auditor"),
                            ("LIBRARY_STAFF", "Library Staff"),
                            ("FINANCE_OFFICER", "Finance Officer"),
                        ],
                        default="STUDENT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "student_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("academic_year", models.IntegerField(blank=True, null=True)),
                ("semester", models.IntegerField(blank=True, null=True)),
                ("program", models.CharField(blank=True, max_length=100, null=True)),
                ("gpa", models.FloatField(blank=True, null=True)),
                ("cgpa", models.FloatField(blank=True, null=True)),
                (
                    "outstanding_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_sharing_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "instructor_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "office_hours",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "staff_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "library_section",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "officer_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("cgpa", models.FloatField()),
                ("total_credits", models.IntegerField()),
                ("verification_code", models.CharField(max_length=50, unique=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "grades",
                    models.ManyToManyField(related_name="transcripts", to="App.grade"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_title", models.CharField(max_length=200)),
                ("student_name", models.CharField(max_length=100)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("file_name", models.CharField(blank=True, max_length=200, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("GRADED", "Graded")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="App.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("program", models.CharField(max_length=100)),
                ("academic_year", models.IntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("GRADUATION", "Graduation"),
                            ("END_OF_YEAR", "End of Year"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("TRANSFER", "Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("initiated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("APPROVED", "Approved"),
                            ("BLOCKED", "Blocked"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                (
                    "digital_stamp_hash",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("stages", models.JSONField(default=list)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clearances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                (
                    "scholarship_type",
                    models.CharField(
                        choices=[
                            ("MERIT_BASED", "Merit Based"),
                            ("NEED_BASED", "Need Based"),
                            ("MOE_SPECIAL_GRANT", "MoE Special Grant"),
                            ("FEMALE_INCENTIVE", "Female Engineering Incentive"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("semester", models.CharField(max_length=20)),
                ("academic_year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ISSUED", "Issued"), ("APPLIED", "Applied")],
                        default="APPLIED",
                        max_length=20,
                    ),
                ),
                ("issued_date", models.DateField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("TELEBIRR", "Telebirr"),
                            ("CBE_BIRR", "CBE Birr"),
                            ("AWASH_BANK", "Awash Bank"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("TUITION", "Tuition"),
                            ("COST_SHARING", "Cost Sharing"),
                            ("DORMITORY", "Dormitory"),
                            ("ID_CARD", "ID Card"),
                            ("REGISTRATION", "Registration"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VERIFIED", "Verified"),
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_by",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructorEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor_name", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=20)),
                ("clarity", models.IntegerField(default=0)),
                ("punctuality", models.IntegerField(default=0)),
                ("helpfulness", models.IntegerField(default=0)),
                ("assessment_fairness", models.IntegerField(default=0)),
                ("overall_rating", models.FloatField(default=0)),
                ("comments", models.TextField(blank=True, null=True)),
                ("semester", models.CharField(max_length=10)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="App.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={"role": "INSTRUCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "STUDENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ExamAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_title", models.CharField(max_length=200)),
                ("student_name", models.CharField(max_length=100)),
                ("answers", models.JSONField(default=dict)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="App.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exam",
            name="questions",
            field=models.ManyToManyField(related_name="exams", to="App.question"),
        ),
        migrations.CreateModel(
            name="CourseOutlineForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=20)),
                ("course_title", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=100)),
                ("syllabus", models.TextField()),
                ("learning_objectives", models.JSONField(default=list)),
                ("weekly_schedule", models.JSONField(default=list)),
                ("continuous_assessment", models.IntegerField(default=50)),
                ("mid_exam", models.IntegerField(default=20)),
                ("final_exam", models.IntegerField(default=30)),
                ("approved_by_dept_head", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outlines",
                        to="App.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF"),
                            ("Video", "Video"),
                            ("Document", "Document"),
                            ("Slide", "Slide"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_url", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materials",
                        to="App.course",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["INSTRUCTOR"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses_taught",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CertificateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("COMPLETION", "Completion"),
                            ("ENROLLMENT", "Enrollment"),
                            ("DEAN_HONOR_ROLL", "Dean Honor Roll"),
                            ("DEGREE_ATTESTATION", "Degree Attestation"),
                        ],
                        max_length=30,
                    ),
                ),
                ("issue_date", models.DateField(auto_now_add=True)),
                ("verification_code", models.CharField(max_length=50, unique=True)),
                ("program", models.CharField(max_length=100)),
                ("is_issued", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_role", models.CharField(max_length=50)),
                ("action", models.CharField(max_length=100)),
                ("entity_type", models.CharField(max_length=50)),
                ("entity_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=20)),
                ("total_sessions", models.IntegerField(default=0)),
                ("attended_sessions", models.IntegerField(default=0)),
                ("attendance_percentage", models.FloatField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("meets_minimum", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to="App.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="App.course",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("posted_by", models.CharField(max_length=100)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="App.course",
                    ),
                ),
            ],
        ),
    ]
