# Generated by Django 4.2.30 on 2026-09-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_campusmediapost_video_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="announcements",
                to="App.course",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="course_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
