# Generated by Django 4.2.30 on 2026-09-11 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_alter_announcement_course_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoomClassSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_code", models.CharField(max_length=20)),
                ("course_title", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("topic", models.TextField(blank=True, null=True)),
                ("instructor_name", models.CharField(max_length=100)),
                ("start_time", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=60)),
                ("meeting_id", models.CharField(max_length=50)),
                ("passcode", models.CharField(blank=True, max_length=50, null=True)),
                ("join_url", models.URLField(max_length=500)),
                ("host_url", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("LIVE", "Live"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        max_length=20,
                    ),
                ),
                ("lecture_notes", models.TextField(blank=True, null=True)),
                (
                    "recording_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "recording_duration",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("active_attendees", models.JSONField(blank=True, default=list)),
                ("chat_messages", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zoom_sessions",
                        to="App.course",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        limit_choices_to={
                            "role__in": ["INSTRUCTOR", "DEPARTMENT_HEAD"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zoom_sessions_taught",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
    ]
