# Generated by Django 4.2.30 on 2026-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_zoomclasssession"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursematerial",
            name="chapter_week",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="file_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="file_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="coursematerial",
            name="instructor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MID_EXAM", "Midterm Exam"),
                    ("FINAL_EXAM", "Final Exam"),
                    ("QUIZ", "Quiz"),
                    ("PRACTICE", "Practice"),
                    ("TEST", "Laboratory Test"),
                    ("EXAM", "General Exam"),
                ],
                default="EXAM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_pushed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="pushed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
